"""
Django settings for storefront project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os 
from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # installed apps
    'django_filters',
    'rest_framework',
    'djoser',
    'debug_toolbar',
    'corsheaders',
    
    # custom apps 
    'playground',
    'store',
    'tags',
    'likes',
    'core',
]

MIDDLEWARE = [
    # -----------------------------------------------------------
    # added middle ware for CORS (Cross Origin Resource Sharing)
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # -----------------------------------------------------------
    # serving static assets in production 
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # -----------------------------------------------------------
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]

# adding allowed origins 
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8001',
    'http://127.0.0.1:8001',
]

ROOT_URLCONF = 'storefront.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'storefront.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# setting static root 
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

#########################################################################################
# ADD : media location
#########################################################################################

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#########################################################################################

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

AUTH_USER_MODEL = 'core.User'

DJOSER = {
    'SERIALIZERS': {
        'user_create': 'core.serializers.UserCreateSerializer',
        'current_user': 'core.serializers.UserSerializer',
    }
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1)
}


#########################################################################################
# ADD : email backend
#########################################################################################

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 2525
DEFAULT_FROM_EMAIL = 'admin@storefront.com'

ADMINS = [
    ('admin', 'admin@storefront.com')
]

#########################################################################################
# ADD : Message Broker (celery) settings
# START WORKER                  : celery -A storefront worker --loglevel=info
# START BEAT                    : celery -A storefront beat
# START CELERY WITH MONITORING  : celery -A storefront flower
#########################################################################################

# configuring the message broker (queue)
CELERY_BROKER_URL = 'redis://localhost:6379/1'

# configuring celery beat scheduler
CELERY_BEAT_SCHEDULE = {
    'notify_customers':{
        'task': 'playground.tasks.notify_customers',
        # 'schedule': crontab(day_of_week=1, hour=7, minute=30), # every monday on 7:30
        # 'schedule': crontab(minute='*/30'), # every 15 minutes
        'schedule': 5, # seconds
        'args': ['Hello World'],
    }
}

#########################################################################################
# ADD : cache
# - Note : we use database number 2 as 1 is used by celery
#########################################################################################

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "TIMEOUT" : 10*60,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

#########################################################################################
# ADD : Logging 
# Log messages have a severity 
# - SEVERITY : DEBUG, INFO, WARNING, ERROR, CRITICAL 
# - severity increases as we go through the list
#########################################################################################

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'handlers': {
        # handler-1 
        'console': {
            'class': 'logging.StreamHandler'
        },
        # handler-2
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'general.log',
            'formatter': 'verbose'
        }
    },
    
    'loggers': {
        # capture any log messages from the playground app 
        # 'playground' : {}, 
        
        # capture any log messages from the playground.view module
        # 'playground.views' : {},
        
        # capture all log messages
        '' : {
            'handlers': ['console', 'file'],
            # only capture logs >= 'X' 
            # instead of hard coding we use an environment variable with INFO as default
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO')
        }
    },
    
    'formatters': {
        # 'simple'
        'verbose': {
            'format': '{asctime} | ({levelname}) | {name} | {message}',
            'style': '{' # str.format()
            # 'style': '$' # sting.Template
        }
    }
}

#########################################################################################