# Generated by Django 4.2.1 on 2023-06-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="slug", field=models.SlugField(default="-"),
        ),
    ]
